name: whitedrywash
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  intl:
  image_picker:
  http:
  shared_preferences:
  flutter_bloc:
  provider:
  uuid:
  path:
  flare_flutter:
  qr_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand_medium.ttf
          style: normal
        - asset: assets/fonts/quicksand_bold.otf
          weight: 700

    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway_regular.ttf
          style: normal
        - asset: assets/fonts/raleway_medium.ttf